language: python
branches:
    only:
        - source
python:
    - 2.7
cache:
    directories:
        - $HOME/.cache/pip
# Installs dependencies
install: pip install -r requirements.pip
# Installs the theme
before_script: pelican-themes -i ./theme/clean-blog
# Uses Makefile for publication
script: make publish github
notifications:
    email:
        on_success: always
        on_failure: always
